// scripts/uploadA1.js
require("dotenv").config({ path: ".env" }); // Make sure you have 'dotenv' installed
const { createClient } = require("@supabase/supabase-js");

// 1. Hardcode your A1 data here (or import it if you convert A1.js to CommonJS)
// Ideally, paste the content of 'const A1 = { ... }' here.
const A1 = {
    title: "A1: Beginner",
    description: "Understand basic, everyday phrases.",
    tests: [
        {
            id: "A1-T1",
            title: "Familie & Freunde",
            questions: [
                {
                    id: "A1-T1-Q1",
                    questionText: "Wie heißt du?",
                    options: ["Ich heiße...", "Ich bin...", "Du heißt..."],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q2",
                    type: "matching", // <--- NEW: Define the type
                    questionText: "Match the words",
                    // Instead of 'options', we use 'pairs'
                    pairs: [
                        { id: "p1", de: "Der Hund", en: "The Dog" },
                        { id: "p2", de: "Die Katze", en: "The Cat" },
                        { id: "p3", de: "Das Auto", en: "The Car" },
                        { id: "p4", de: "Das Haus", en: "The House" },
                    ],
                },
                // {
                //     id: "A1-T1-Q2",
                //     questionText: "Woher kommst du?",
                //     options: ["Ich komme aus...", "Ich bin in...", "Du kommst..."],
                //     correctAnswerIndex: 0,
                // },
                // {
                //     id: "A1-T1-Q3",
                //     questionText: "Wie alt bist du?",
                //     options: ["Ich habe 20 Jahre", "Ich bin 20 Jahre alt", "Ich bin 20 alt"],
                //     correctAnswerIndex: 1,
                // },
                {
                    id: "A1-T1-Q3",
                    type: "sentence", // <--- NEW TYPE
                    questionText: "Translate this sentence:",
                    englishText: "I am hungry",
                    correctSentence: ["Ich", "habe", "Hunger"], // The correct order
                    // You can add extra "distractor" words here if you want to make it harder
                    options: ["Ich", "bist", "Hunger", "habe", "Wasser"],
                },
                {
                    id: "A1-T1-Q4",
                    questionText: "Was ist dein Beruf?",
                    options: ["Ich bin...", "Ich habe...", "Ich mache..."],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q5",
                    questionText: "Das ist ___ Bruder.",
                    options: ["der", "die", "das"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q6",
                    questionText: "Er ___ in Berlin.",
                    options: ["wohnt", "wohne", "wohnen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q7",
                    questionText: "Wie ___ es dir?",
                    options: ["geht", "bist", "hast"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q8",
                    questionText: "Ich habe ___ Katze.",
                    options: ["eine", "einen", "ein"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q9",
                    questionText: "Sie ist ___.",
                    options: ["verheiratet", "groß", "schnell"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q10",
                    questionText: "Das ist ___ Vater.",
                    options: ["mein", "meine", "meinen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q11",
                    questionText: "Wo ___ du?",
                    options: ["wohnst", "wohne", "wohnt"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q12",
                    questionText: "Meine Mutter heißt ___.",
                    options: ["Anna", "groß", "blau"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q13",
                    questionText: "Ich ___ aus Spanien.",
                    options: ["komme", "kommst", "kommt"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q14",
                    questionText: "Bist du Student?",
                    options: ["Ja, ich bin...", "Nein, ich habe...", "Ich esse..."],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q15",
                    questionText: "Das ist ___ Auto.",
                    options: ["ein", "eine", "einen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q16",
                    questionText: "Sie ___ Kinder.",
                    options: ["haben", "habt", "hat"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q17",
                    questionText: "Mein Bruder ist ___.",
                    options: ["Arzt", "Auto", "Apfel"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q18",
                    questionText: "Was ___ du?",
                    options: ["machst", "macht", "mache"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q19",
                    questionText: "Er hat ___ Hund.",
                    options: ["einen", "eine", "ein"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q20",
                    questionText: "Das ist ___ Haus.",
                    options: ["unser", "unsere", "unseren"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q21",
                    questionText: "Meine Schwester ___ 20 Jahre alt.",
                    options: ["ist", "habe", "bin"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q22",
                    questionText: "Ich ___ gern Pizza.",
                    options: ["esse", "esst", "isst"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q23",
                    questionText: "Das sind ___ Eltern.",
                    options: ["meine", "mein", "meinen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q24",
                    questionText: "Er ___ kein Auto.",
                    options: ["hat", "habe", "hast"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q25",
                    questionText: "Wie ist dein ___?",
                    options: ["Name", "Alt", "Komme"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q26",
                    questionText: "Ich ___ nicht verheiratet.",
                    options: ["bin", "habe", "wohne"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q27",
                    questionText: "Das ist ___ Tante.",
                    options: ["meine", "mein", "meinen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q28",
                    questionText: "Wir ___ in Deutschland.",
                    options: ["wohnen", "wohnt", "wohne"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q29",
                    questionText: "Was sprichst du?",
                    options: ["Ich spreche...", "Ich bin...", "Ich habe..."],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T1-Q30",
                    questionText: "Hast du Kinder?",
                    options: ["Ja, ich habe...", "Ja, ich bin...", "Ja, ich spiele..."],
                    correctAnswerIndex: 0,
                },
            ],
        },
        {
            id: "A1-T2",
            title: "Essen & Trinken",
            questions: [
                {
                    id: "A1-T2-Q1",
                    questionText: "Was trinkst du gern?",
                    options: ["Ich trinke gern...", "Ich esse gern...", "Ich habe gern..."],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q2",
                    questionText: "Was ___ du gern?",
                    options: ["isst", "esse", "essen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q3",
                    questionText: "Ich möchte ___ Apfel.",
                    options: ["einen", "eine", "ein"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q4",
                    questionText: "Ich esse ___ Banane.",
                    options: ["einen", "eine", "ein"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T2-Q5",
                    questionText: "Ich kaufe ___ Brot.",
                    options: ["einen", "eine", "ein"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T2-Q6",
                    questionText: "Er ___ eine Pizza.",
                    options: ["isst", "esse", "essen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q7",
                    questionText: "Wir ___ Saft.",
                    options: ["trinkt", "trinken", "trinke"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T2-Q8",
                    questionText: "Ich ___ Kaffee.",
                    options: ["mag", "mögen", "magst"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q9",
                    questionText: "Ich habe ___ .",
                    options: ["Hunger", "Essen", "Trinken"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q10",
                    questionText: "Ich habe ___ .",
                    options: ["Durst", "Wasser", "Saft"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q11",
                    questionText: "Was isst du zum ___?",
                    options: ["Frühstück", "Buch", "Auto"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q12",
                    questionText: "Ein Apfel ist ___ .",
                    options: ["Obst", "Gemüse", "Fleisch"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q13",
                    questionText: "Eine Tomate ist ___ .",
                    options: ["Gemüse", "Obst", "Brot"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q14",
                    questionText: "Was ___ der Kaffee?",
                    options: ["kostet", "kosten", "kauft"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q15",
                    questionText: "Ich ___ gern ein Wasser.",
                    options: ["möchte", "mag", "habe"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q16",
                    questionText: "Ich mag ___ Fisch.",
                    options: ["keinen", "nicht", "nein"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q17",
                    questionText: "Er trinkt ___ Milch.",
                    options: ["die", "der", "das"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q18",
                    questionText: "Was gibt es zum ___?",
                    options: ["Abendessen", "Morgen", "Tag"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q19",
                    questionText: "___ du Pizza?",
                    options: ["Magst", "Mögen", "Mag"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q20",
                    questionText: "Das ist ___ .",
                    options: ["Käse", "Buch", "Auto"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q21",
                    questionText: "Das ist ___ .",
                    options: ["Wurst", "Stuhl", "Tisch"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q22",
                    questionText: "Das sind ___ .",
                    options: ["Eier", "Ei", "Eies"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q23",
                    questionText: "Eine Flasche ___ .",
                    options: ["Wasser", "Brot", "Käse"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q24",
                    questionText: "Eine Tasse ___ .",
                    options: ["Kaffee", "Wurst", "Reis"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q25",
                    questionText: "Kaffee ist ___ .",
                    options: ["lecker", "schlecht", "groß"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q26",
                    questionText: "Ich ___ ein Brot.",
                    options: ["kaufe", "kaufst", "kauft"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q27",
                    questionText: "Ich esse um 12 Uhr ___ .",
                    options: ["Mittagessen", "Frühstück", "Abendessen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q28",
                    questionText: "Wir ___ Hunger.",
                    options: ["haben", "habt", "hat"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q29",
                    questionText: "Er mag ___ Tee.",
                    options: ["keinen", "nicht", "nein"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T2-Q30",
                    questionText: "Was ist dein Lieblingsessen?",
                    options: ["Mein Lieblingsessen ist...", "Ich bin...", "Ich habe..."],
                    correctAnswerIndex: 0,
                },
            ],
        },
        {
            id: "A1-T3",
            title: "Zahlen, Uhrzeit & Kalender",
            questions: [
                {
                    id: "A1-T3-Q1",
                    questionText: "Wie viel ist 2 + 2?",
                    options: ["Fünf", "Vier", "Drei"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T3-Q2",
                    questionText: "Was kommt nach Montag?",
                    options: ["Dienstag", "Mittwoch", "Sonntag"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T3-Q3",
                    questionText: "Wie spät ist es? Es ist 10:00 Uhr.",
                    options: ["Es ist zehn", "Es ist Uhr zehn", "Es ist zehn Uhr"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q4",
                    questionText: "Welche Zahl ist das: 7?",
                    options: ["Acht", "Sieben", "Sechs"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T3-Q5",
                    questionText: "Welcher Monat kommt nach Januar?",
                    options: ["Februar", "Dezember", "März"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T3-Q6",
                    questionText: "Es ist 14:00 Uhr. Das ist ___ Uhr.",
                    options: ["vierzehn", "zwei", "vier"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T3-Q7",
                    questionText: "Wie viele Tage hat eine Woche?",
                    options: ["Fünf", "Zehn", "Sieben"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q8",
                    questionText: "Welche Zahl ist das: 20?",
                    options: ["Zwei", "Zwölf", "Zwanzig"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q9",
                    questionText: "Wann ist das Wochenende?",
                    options: ["Mittwoch", "Montag und Dienstag", "Samstag und Sonntag"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q10",
                    questionText: "Es ist 9:30 Uhr. Es ist halb ___.",
                    options: ["neun", "zehn", "dreißig"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T3-Q11",
                    questionText: "Welcher Monat ist der erste im Jahr?",
                    options: ["Dezember", "Januar", "Februar"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T3-Q12",
                    questionText: "Welche Zahl ist das: 13?",
                    options: ["Drei", "Dreizehn", "Dreißig"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T3-Q13",
                    questionText: "Was ist der letzte Tag der Woche?",
                    options: ["Samstag", "Montag", "Sonntag"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q14",
                    questionText: "Es ist 15:15 Uhr. Es ist Viertel nach ___.",
                    options: ["drei", "vier", "fünfzehn"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T3-Q15",
                    questionText: "Wie viele Monate hat ein Jahr?",
                    options: ["Zehn", "Sieben", "Zwölf"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q16",
                    questionText: "Welche Zahl ist das: 50?",
                    options: ["Fünfzig", "Fünfzehn", "Fünf"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T3-Q17",
                    questionText: "Welcher Tag kommt vor Freitag?",
                    options: ["Samstag", "Donnerstag", "Mittwoch"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T3-Q18",
                    questionText: "Es ist 8:45 Uhr. Es ist Viertel vor ___.",
                    options: ["fünfzehn", "acht", "neun"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q19",
                    questionText: "Welche Zahl ist das: 100?",
                    options: ["Hundert", "Tausend", "Zehn"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T3-Q20",
                    questionText: "Welcher Monat kommt vor Mai?",
                    options: ["Juni", "April", "März"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T3-Q21",
                    questionText: "Wie viel ist 10 + 5?",
                    options: ["Zehn", "Fünfzig", "Fünfzehn"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q22",
                    questionText: "Was ist 'Tuesday' auf Deutsch?",
                    options: ["Donnerstag", "Dienstag", "Drei"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T3-Q23",
                    questionText: "Es ist 12:00 Uhr mittags. Es ist ___.",
                    options: ["Mitternacht", "Zwölf", "Mittag"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q24",
                    questionText: "Welche Zahl ist das: 11?",
                    options: ["Elf", "Eins", "Zehn"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T3-Q25",
                    questionText: "Welcher Monat ist 'July'?",
                    options: ["Juni", "Januar", "Juli"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q26",
                    questionText: "Wie viel ist 30 - 10?",
                    options: ["Dreißig", "Zwanzig", "Vierzig"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T3-Q27",
                    questionText: "Was ist 'Wednesday'?",
                    options: ["Mittwoch", "Montag", "Dienstag"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T3-Q28",
                    questionText: "Es ist 00:00 Uhr. Es ist ___.",
                    options: ["Mittag", "Null", "Mitternacht"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T3-Q29",
                    questionText: "Welche Zahl ist das: 12?",
                    options: ["Zwei", "Zwölf", "Zwanzig"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T3-Q30",
                    questionText: "Welcher Monat ist 'December'?",
                    options: ["Dezember", "Dienstag", "Donnerstag"],
                    correctAnswerIndex: 0,
                },
            ],
        },
        {
            id: "A1-T4",
            title: "Wohnen & Möbel",
            questions: [
                {
                    id: "A1-T4-Q1",
                    questionText: "Wo wohnst du?",
                    options: ["Ich wohne in...", "Ich bin...", "Ich habe..."],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q2",
                    questionText: "Das ist ___ Bett.",
                    options: ["eine", "einen", "ein"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T4-Q3",
                    questionText: "Das ist ___ Stuhl.",
                    options: ["ein", "eine", "einen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q4",
                    questionText: "Das ist ___ Lampe.",
                    options: ["eine", "einen", "ein"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q5",
                    questionText: "Ich habe ___ Tisch.",
                    options: ["einen", "eine", "ein"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q6",
                    questionText: "Wie ist deine ___?",
                    options: ["Haus", "Adresse", "Stuhl"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T4-Q7",
                    questionText: "Die Wohnung ___ klein.",
                    options: ["ist", "habe", "wohnt"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q8",
                    questionText: "Das ___ ist groß.",
                    options: ["Sofa", "Lampe", "Stuhl"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q9",
                    questionText: "Er ___ ein neues Bett.",
                    options: ["hat", "ist", "wohnt"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q10",
                    questionText: "Wo ist ___ Toilette?",
                    options: ["das", "der", "die"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T4-Q11",
                    questionText: "Das Haus hat ___ Garten.",
                    options: ["einen", "eine", "ein"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q12",
                    questionText: "Das ist die ___.",
                    options: ["Küche", "Auto", "Buch"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q13",
                    questionText: "Ich schlafe im ___.",
                    options: ["Garten", "Küche", "Schlafzimmer"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T4-Q14",
                    questionText: "Der ___ ist im Wohnzimmer.",
                    options: ["Schrank", "Bett", "Kühlschrank"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q15",
                    questionText: "Das ___ ist modern.",
                    options: ["Haus", "Tische", "Stühle"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q16",
                    questionText: "Die Lampe ___ an der Decke.",
                    options: ["steht", "liegt", "hängt"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T4-Q17",
                    questionText: "Wie viele ___ hat die Wohnung?",
                    options: ["Zimmer", "Haus", "Küche"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q18",
                    questionText: "Das ist ___ Badezimmer.",
                    options: ["der", "die", "das"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T4-Q19",
                    questionText: "Der Teppich ___ auf dem Boden.",
                    options: ["liegt", "steht", "hängt"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q20",
                    questionText: "Ich wohne im ___ Stock.",
                    options: ["zweiten", "zwei", "zwei Stock"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q21",
                    questionText: "Hast du ___ Balkon?",
                    options: ["ein", "eine", "einen"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T4-Q22",
                    questionText: "Die Küche ist ___.",
                    options: ["neu", "alt", "groß"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q23",
                    questionText: "Das ___ ist im Badezimmer.",
                    options: ["Waschbecken", "Bett", "Sofa"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q24",
                    questionText: "Ich koche in der ___.",
                    options: ["Küche", "Garage", "Balkon"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q25",
                    questionText: "Der ___ ist voll.",
                    options: ["Kühlschrank", "Lampe", "Stuhl"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q26",
                    questionText: "Das sind ___ Bücher.",
                    options: ["die", "der", "das"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q27",
                    questionText: "Das Fenster ist ___.",
                    options: ["Haus", "geschlossen", "Stuhl"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T4-Q28",
                    questionText: "Wo ist der ___?",
                    options: ["Schlüssel", "Tür", "Wand"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q29",
                    questionText: "Mein Zimmer ist ___.",
                    options: ["gemütlich", "essen", "trinken"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T4-Q30",
                    questionText: "Ich sitze auf dem ___.",
                    options: ["Stuhl", "Tisch", "Bett"],
                    correctAnswerIndex: 0,
                },
            ],
        },
        {
            id: "A1-T5",
            title: "Im Restaurant & Einkaufen",
            questions: [
                {
                    id: "A1-T5-Q1",
                    questionText: "Ich möchte ___.",
                    options: ["bestellen", "wohnen", "schlafen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q2",
                    questionText: "Ich möchte bitte ___.",
                    options: ["lesen", "zahlen", "singen"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T5-Q3",
                    questionText: "Was ___ das?",
                    options: ["kostet", "bist", "sind"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q4",
                    questionText: "Ich nehme ___ Kaffee.",
                    options: ["eine", "einen", "ein"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T5-Q5",
                    questionText: "Ich brauche ___ Tomaten.",
                    options: ["keine", "kein", "keinen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q6",
                    questionText: "Die ___ bitte.",
                    options: ["Rechnung", "Haus", "Auto"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q7",
                    questionText: "Wo ___ ich Brot?",
                    options: ["finde", "bin", "habe"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q8",
                    questionText: "Haben Sie ___?",
                    options: ["einen Tisch", "ein Auto", "ein Bett"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q9",
                    questionText: "Das macht 10 ___.",
                    options: ["Euro", "Kilo", "Liter"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q10",
                    questionText: "Ich hätte gern ___ Wasser.",
                    options: ["ein", "eine", "einen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q11",
                    questionText: "Ein ___ Äpfel, bitte.",
                    options: ["Stück", "Liter", "Kilo"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T5-Q12",
                    questionText: "Was ist die ___?",
                    options: ["Speisekarte", "Buch", "Stuhl"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q13",
                    questionText: "Der Pullover ist zu ___.",
                    options: ["groß", "essen", "trinken"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q14",
                    questionText: "Kann ich mit ___ zahlen?",
                    options: ["Karte", "Auto", "Haus"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q15",
                    questionText: "Das Essen ist ___.",
                    options: ["kalt", "schnell", "groß"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q16",
                    questionText: "Ich ___ im Supermarkt.",
                    options: ["bin", "habe", "gehe"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q17",
                    questionText: "Wo ist die ___?",
                    options: ["Kasse", "Schule", "Bank"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q18",
                    questionText: "Ich brauche ___ Jacke.",
                    options: ["eine", "einen", "ein"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q19",
                    questionText: "Das Hemd gefällt mir ___.",
                    options: ["gut", "essen", "rot"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q20",
                    questionText: "Haben Sie das in ___?",
                    options: ["Rot", "Groß", "Neu"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q21",
                    questionText: "Ich ___ eine Suppe.",
                    options: ["esse", "trinke", "schlafe"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q22",
                    questionText: "Das ___ ist lecker.",
                    options: ["Bier", "Buch", "Stift"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q23",
                    questionText: "Wo kann ich ___ anprobieren?",
                    options: ["die Hose", "das Auto", "das Essen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q24",
                    questionText: "Guten ___!",
                    options: ["Appetit", "Tag", "Morgen"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q25",
                    questionText: "Zusammen oder ___?",
                    options: ["getrennt", "klein", "groß"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q26",
                    questionText: "Das macht 5,50 €.",
                    options: ["Fünf Euro fünfzig", "Fünfzig", "Fünf und fünfzig"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q27",
                    questionText: "Ich ___ nur.",
                    options: ["schaue", "esse", "schlafe"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q28",
                    questionText: "Der Fisch ___ gut.",
                    options: ["schmeckt", "kostet", "ist"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q29",
                    questionText: "Als ___ nehme ich ein Eis.",
                    options: ["Nachtisch", "Vorspeise", "Getränk"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T5-Q30",
                    questionText: "Das ist zu ___.",
                    options: ["teuer", "billig", "gut"],
                    correctAnswerIndex: 0,
                },
            ],
        },
        {
            id: "A1-T6",
            title: "A1 Mixed Review",
            questions: [
                // // --- 10 Sentence Questions ---
                // {
                //     id: "A1-T6-Q21",
                //     type: "sentence",
                //     questionText: "Translate this sentence:",
                //     englishText: "My name is Anna.",
                //     correctSentence: ["Mein", "Name", "ist", "Anna"],
                //     options: ["ist", "Anna", "Mein", "Name", "Ich"],
                // },
                // {
                //     id: "A1-T6-Q22",
                //     type: "sentence",
                //     questionText: "Translate this sentence:",
                //     englishText: "I come from Spain.",
                //     correctSentence: ["Ich", "komme", "aus", "Spanien"],
                //     options: ["Spanien", "komme", "Ich", "aus", "bin"],
                // },
                // {
                //     id: "A1-T6-Q23",
                //     type: "sentence",
                //     questionText: "Translate this sentence:",
                //     englishText: "What are you drinking?",
                //     correctSentence: ["Was", "trinkst", "du"],
                //     options: ["du", "Was", "trinkst", "essen"],
                // },
                // {
                //     id: "A1-T6-Q24",
                //     type: "sentence",
                //     questionText: "Translate this sentence:",
                //     englishText: "I would like a coffee.",
                //     correctSentence: ["Ich", "möchte", "einen", "Kaffee"],
                //     options: ["Kaffee", "Ich", "einen", "möchte", "eine"],
                // },
                // {
                //     id: "A1-T6-Q25",
                //     type: "sentence",
                //     questionText: "Translate this sentence:",
                //     englishText: "He lives in Berlin.",
                //     correctSentence: ["Er", "wohnt", "in", "Berlin"],
                //     options: ["in", "wohnt", "Berlin", "Er", "Wir"],
                // },
                // {
                //     id: "A1-T6-Q26",
                //     type: "sentence",
                //     questionText: "Translate this sentence:",
                //     englishText: "How old are you?",
                //     correctSentence: ["Wie", "alt", "bist", "du"],
                //     options: ["alt", "du", "Wie", "bist", "sind"],
                // },
                // {
                //     id: "A1-T6-Q27",
                //     type: "sentence",
                //     questionText: "Translate this sentence:",
                //     englishText: "I have two children.",
                //     correctSentence: ["Ich", "habe", "zwei", "Kinder"],
                //     options: ["Kinder", "habe", "zwei", "Ich", "sind"],
                // },
                // {
                //     id: "A1-T6-Q28",
                //     type: "sentence",
                //     questionText: "Translate this sentence:",
                //     englishText: "Where is the train station?",
                //     correctSentence: ["Wo", "ist", "der", "Bahnhof"],
                //     options: ["Bahnhof", "Wo", "der", "ist", "das"],
                // },
                // {
                //     id: "A1-T6-Q29",
                //     type: "sentence",
                //     questionText: "Translate this sentence:",
                //     englishText: "It is half past ten.",
                //     correctSentence: ["Es", "ist", "halb", "elf"],
                //     options: ["zehn", "ist", "Es", "elf", "halb"],
                // },
                // {
                //     id: "A1-T6-Q30",
                //     type: "sentence",
                //     questionText: "Translate this sentence:",
                //     englishText: "I am eating an apple.",
                //     correctSentence: ["Ich", "esse", "einen", "Apfel"],
                //     options: ["esse", "Apfel", "einen", "eine", "Ich"],
                // },
                {
                    id: "A1-T6-Q21",
                    type: "sentence",
                    questionText: "Translate this sentence:",
                    englishText: "Tomorrow I am going to the supermarket with my mother.",
                    correctSentence: ["Morgen", "gehe", "ich", "mit", "meiner", "Mutter", "in", "den", "Supermarkt"],
                    options: [
                        "in",
                        "gehe",
                        "Mutter",
                        "den",
                        "Supermarkt",
                        "ich",
                        "mit",
                        "meiner",
                        "Morgen",
                        "fahre",
                        "mein",
                        "ins",
                    ],
                },
                {
                    id: "A1-T6-Q22",
                    type: "sentence",
                    questionText: "Translate this sentence:",
                    englishText: "My brother is giving me a book for my birthday.",
                    correctSentence: ["Mein", "Bruder", "gibt", "mir", "ein", "Buch", "zum", "Geburtstag"],
                    options: [
                        "ein",
                        "gibt",
                        "Geburtstag",
                        "mir",
                        "Mein",
                        "Bruder",
                        "Buch",
                        "zum",
                        "schenkt",
                        "mich",
                        "dem",
                    ],
                },
                {
                    id: "A1-T6-Q23",
                    type: "sentence",
                    questionText: "Translate this sentence:",
                    englishText: "I would like a cup of coffee with milk, please.",
                    correctSentence: ["Ich", "hätte", "gern", "eine", "Tasse", "Kaffee", "mit", "Milch", "bitte"],
                    options: [
                        "Tasse",
                        "gern",
                        "Milch",
                        "eine",
                        "bitte",
                        "Ich",
                        "hätte",
                        "Kaffee",
                        "mit",
                        "möchte",
                        "ohne",
                        "Zucker",
                    ],
                },
                {
                    id: "A1-T6-Q24",
                    type: "sentence",
                    questionText: "Translate this sentence:",
                    englishText: "On the weekend we visit our grandparents in the city.",
                    correctSentence: [
                        "Am",
                        "Wochenende",
                        "besuchen",
                        "wir",
                        "unsere",
                        "Großeltern",
                        "in",
                        "der",
                        "Stadt",
                    ],
                    options: [
                        "Stadt",
                        "besuchen",
                        "in",
                        "wir",
                        "Am",
                        "Großeltern",
                        "der",
                        "Wochenende",
                        "unsere",
                        "sehe",
                        "unser",
                        "Dorf",
                    ],
                },
                {
                    id: "A1-T6-Q25",
                    type: "sentence",
                    questionText: "Translate this sentence:",
                    englishText: "I have to work in the office today until 5 o'clock.",
                    correctSentence: ["Ich", "muss", "heute", "bis", "5", "Uhr", "im", "Büro", "arbeiten"],
                    options: [
                        "Uhr",
                        "muss",
                        "heute",
                        "5",
                        "im",
                        "Büro",
                        "Ich",
                        "arbeiten",
                        "bis",
                        "will",
                        "von",
                        "Hause",
                    ],
                },
                {
                    id: "A1-T6-Q26",
                    type: "sentence",
                    questionText: "Translate this sentence:",
                    englishText: "My sister can play the guitar and the piano very well.",
                    correctSentence: [
                        "Meine",
                        "Schwester",
                        "kann",
                        "sehr",
                        "gut",
                        "Gitarre",
                        "und",
                        "Klavier",
                        "spielen",
                    ],
                    options: [
                        "sehr",
                        "kann",
                        "spielen",
                        "und",
                        "Gitarre",
                        "Klavier",
                        "gut",
                        "Meine",
                        "Schwester",
                        "spielt",
                        "oder",
                        "auch",
                    ],
                },
                {
                    id: "A1-T6-Q27",
                    type: "sentence",
                    questionText: "Translate this sentence:",
                    englishText: "We are traveling by train to Hamburg on Friday morning.",
                    correctSentence: ["Wir", "fahren", "am", "Freitagmorgen", "mit", "dem", "Zug", "nach", "Hamburg"],
                    options: [
                        "Zug",
                        "Hamburg",
                        "mit",
                        "fahren",
                        "nach",
                        "dem",
                        "Freitagmorgen",
                        "Wir",
                        "am",
                        "fliegen",
                        "den",
                        "Auto",
                    ],
                },
                {
                    id: "A1-T6-Q28",
                    type: "sentence",
                    questionText: "Translate this sentence:",
                    englishText: "Did you buy bread and two bottles of milk at the supermarket?",
                    correctSentence: [
                        "Hast",
                        "du",
                        "im",
                        "Supermarkt",
                        "Brot",
                        "und",
                        "zwei",
                        "Flaschen",
                        "Milch",
                        "gekauft",
                    ],
                    options: [
                        "du",
                        "Milch",
                        "im",
                        "Hast",
                        "gekauft",
                        "Supermarkt",
                        "und",
                        "Brot",
                        "Flaschen",
                        "zwei",
                        "Käse",
                        "eine",
                        "kaufen",
                    ],
                },
                {
                    id: "A1-T6-Q29",
                    type: "sentence",
                    questionText: "Translate this sentence:",
                    englishText: "I have to clean my room today because it is very dirty.",
                    correctSentence: [
                        "Ich",
                        "muss",
                        "heute",
                        "mein",
                        "Zimmer",
                        "aufräumen",
                        "weil",
                        "es",
                        "sehr",
                        "schmutzig",
                        "ist",
                    ],
                    options: [
                        "Zimmer",
                        "es",
                        "sehr",
                        "ist",
                        "aufräumen",
                        "muss",
                        "heute",
                        "mein",
                        "Ich",
                        "schmutzig",
                        "weil",
                        "denn",
                        "sauber",
                        "war",
                    ],
                },
                {
                    id: "A1-T6-Q30",
                    type: "sentence",
                    questionText: "Translate this sentence:",
                    englishText: "Would you like to go to the cinema with me this evening?",
                    correctSentence: ["Möchtest", "du", "heute", "Abend", "mit", "mir", "ins", "Kino", "gehen"],
                    options: [
                        "Abend",
                        "Kino",
                        "du",
                        "gehen",
                        "mit",
                        "Möchtest",
                        "mir",
                        "heute",
                        "ins",
                        "Willst",
                        "morgen",
                        "im",
                    ],
                },
                // --- 10 Standard Questions ---
                {
                    id: "A1-T6-Q1",
                    type: "standard",
                    questionText: "Wie geht ___ Ihnen?",
                    translation: "How are you? (formal)",
                    options: ["es", "Sie", "dir"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T6-Q2",
                    type: "standard",
                    questionText: "Das ist ___ Auto.",
                    translation: "That is a car.",
                    options: ["eine", "ein", "einen"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T6-Q3",
                    type: "standard",
                    questionText: "Ich habe ___ Hund.",
                    translation: "I have a dog.",
                    options: ["ein", "eine", "einen"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T6-Q4",
                    type: "standard",
                    questionText: "Was ___ du von Beruf?",
                    translation: "What is your profession?",
                    options: ["sind", "ist", "bist"],
                    correctAnswerIndex: 2,
                },
                {
                    id: "A1-T6-Q5",
                    type: "standard",
                    questionText: "Er ___ gern Pizza.",
                    translation: "He likes to eat pizza.",
                    options: ["esse", "isst", "esst"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T6-Q6",
                    type: "standard",
                    questionText: "Wie viel ___ die Tomaten?",
                    translation: "How much do the tomatoes cost?",
                    options: ["kostet", "kosten", "kauft"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T6-Q7",
                    type: "standard",
                    questionText: "Es ist Viertel ___ neun.",
                    translation: "It is quarter past eight.",
                    options: ["vor", "nach", "halb"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T6-Q8",
                    type: "standard",
                    questionText: "Ich wohne ___ der Schillerstraße.",
                    translation: "I live on Schiller Street.",
                    options: ["in", "auf", "an"],
                    correctAnswerIndex: 0,
                },
                {
                    id: "A1-T6-Q9",
                    type: "standard",
                    questionText: "Das sind ___ Eltern.",
                    translation: "Those are my parents.",
                    options: ["mein", "meine", "meinen"],
                    correctAnswerIndex: 1,
                },
                {
                    id: "A1-T6-Q10",
                    type: "standard",
                    questionText: "Der Stuhl ist ___ dem Tisch.",
                    translation: "The chair is next to the table.",
                    options: ["an", "neben", "auf"],
                    correctAnswerIndex: 1,
                },

                // --- 10 Matching Questions (6 pairs each) ---
                {
                    id: "A1-T6-Q11",
                    type: "matching",
                    questionText: "Match the Numbers",
                    translation: "Match the Numbers",
                    pairs: [
                        { id: "p1", de: "drei", en: "three" },
                        { id: "p2", de: "acht", en: "eight" },
                        { id: "p3", de: "zwölf", en: "twelve" },
                        { id: "p4", de: "fünf", en: "five" },
                        { id: "p5", de: "neun", en: "nine" },
                        { id: "p6", de: "eins", en: "one" },
                    ],
                },
                {
                    id: "A1-T6-Q12",
                    type: "matching",
                    questionText: "Match the Food",
                    translation: "Match the Food",
                    pairs: [
                        { id: "p1", de: "Das Brot", en: "The Bread" },
                        { id: "p2", de: "Die Butter", en: "The Butter" },
                        { id: "p3", de: "Der Käse", en: "The Cheese" },
                        { id: "p4", de: "Das Ei", en: "The Egg" },
                        { id: "p5", de: "Der Apfel", en: "The Apple" },
                        { id: "p6", de: "Die Milch", en: "The Milk" },
                    ],
                },
                {
                    id: "A1-T6-Q13",
                    type: "matching",
                    questionText: "Match the Verbs",
                    translation: "Match the Verbs",
                    pairs: [
                        { id: "p1", de: "haben", en: "to have" },
                        { id: "p2", de: "sein", en: "to be" },
                        { id: "p3", de: "gehen", en: "to go" },
                        { id: "p4", de: "sprechen", en: "to speak" },
                        { id: "p5", de: "essen", en: "to eat" },
                        { id: "p6", de: "trinken", en: "to drink" },
                    ],
                },
                {
                    id: "A1-T6-Q14",
                    type: "matching",
                    questionText: "Match the Family",
                    translation: "Match the Family",
                    pairs: [
                        { id: "p1", de: "Der Vater", en: "The Father" },
                        { id: "p2", de: "Die Mutter", en: "The Mother" },
                        { id: "p3", de: "Der Bruder", en: "The Brother" },
                        { id: "p4", de: "Die Schwester", en: "The Sister" },
                        { id: "p5", de: "Der Sohn", en: "The Son" },
                        { id: "p6", de: "Die Tochter", en: "The Daughter" },
                    ],
                },
                {
                    id: "A1-T6-Q15",
                    type: "matching",
                    questionText: "Match the Days",
                    translation: "Match the Days",
                    pairs: [
                        { id: "p1", de: "Montag", en: "Monday" },
                        { id: "p2", de: "Mittwoch", en: "Wednesday" },
                        { id: "p3", de: "Freitag", en: "Friday" },
                        { id: "p4", de: "Sonntag", en: "Sunday" },
                        { id: "p5", de: "Dienstag", en: "Tuesday" },
                        { id: "p6", de: "Samstag", en: "Saturday" },
                    ],
                },
                {
                    id: "A1-T6-Q16",
                    type: "matching",
                    questionText: "Match the Furniture",
                    translation: "Match the Furniture",
                    pairs: [
                        { id: "p1", de: "Der Tisch", en: "The Table" },
                        { id: "p2", de: "Der Stuhl", en: "The Chair" },
                        { id: "p3", de: "Das Bett", en: "The Bed" },
                        { id: "p4", de: "Das Sofa", en: "The Sofa" },
                        { id: "p5", de: "Die Lampe", en: "The Lamp" },
                        { id: "p6", de: "Der Schrank", en: "The Cabinet" },
                    ],
                },
                {
                    id: "A1-T6-Q17",
                    type: "matching",
                    questionText: "Match the Drinks",
                    translation: "Match the Drinks",
                    pairs: [
                        { id: "p1", de: "Das Wasser", en: "The Water" },
                        { id: "p2", de: "Der Kaffee", en: "The Coffee" },
                        { id: "p3", de: "Der Tee", en: "The Tea" },
                        { id: "p4", de: "Der Saft", en: "The Juice" },
                        { id: "p5", de: "Das Bier", en: "The Beer" },
                        { id: "p6", de: "Der Wein", en: "The Wine" },
                    ],
                },
                {
                    id: "A1-T6-Q18",
                    type: "matching",
                    questionText: "Match the Colors",
                    translation: "Match the Colors",
                    pairs: [
                        { id: "p1", de: "rot", en: "red" },
                        { id: "p2", de: "grün", en: "green" },
                        { id: "p3", de: "blau", en: "blue" },
                        { id: "p4", de: "gelb", en: "yellow" },
                        { id: "p5", de: "schwarz", en: "black" },
                        { id: "p6", de: "weiß", en: "white" },
                    ],
                },
                {
                    id: "A1-T6-Q19",
                    type: "matching",
                    questionText: "Match the Questions",
                    translation: "Match the Questions",
                    pairs: [
                        { id: "p1", de: "Wie?", en: "How?" },
                        { id: "p2", de: "Was?", en: "What?" },
                        { id: "p3", de: "Wo?", en: "Where?" },
                        { id: "p4", de: "Wer?", en: "Who?" },
                        { id: "p5", de: "Wann?", en: "When?" },
                        { id: "p6", de: "Warum?", en: "Why?" },
                    ],
                },
                {
                    id: "A1-T6-Q20",
                    type: "matching",
                    questionText: "Match the Body Parts",
                    translation: "Match the Body Parts",
                    pairs: [
                        { id: "p1", de: "Der Kopf", en: "The Head" },
                        { id: "p2", de: "Die Hand", en: "The Hand" },
                        { id: "p3", de: "Der Fuß", en: "The Foot" },
                        { id: "p4", de: "Das Auge", en: "The Eye" },
                        { id: "p5", de: "Die Nase", en: "The Nose" },
                        { id: "p6", de: "Der Mund", en: "The Mouth" },
                    ],
                },
            ],
        },
    ],
};

// 2. Init Supabase (use SERVICE_ROLE key to bypass RLS for writing)
// You need to add EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY to your .env for this script
const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

const uploadData = async () => {
    console.log("🚀 Starting upload for Level A1...");

    // A. Upload Level
    const { error: levelError } = await supabase.from("levels").upsert({
        id: "A1",
        title: A1.title,
        description: A1.description,
    });
    if (levelError) return console.error("Level Error:", levelError);

    for (const test of A1.tests) {
        console.log(`  📂 Uploading Test: ${test.title}`);

        // B. Upload Test
        const { error: testError } = await supabase.from("tests").upsert({
            id: test.id,
            level_id: "A1",
            title: test.title,
        });
        if (testError) console.error("    Test Error:", testError);

        // C. Upload Questions
        const questionsPayload = test.questions.map((q, index) => {
            // Separate common fields from specific "content" fields
            const { id, questionText, type = "standard", ...rest } = q;

            return {
                id: q.id,
                test_id: test.id,
                question_text: questionText,
                type: type,
                sort_order: index,
                content: rest, // Stores options, pairs, correctSentence, etc.
            };
        });

        const { error: qError } = await supabase.from("questions").upsert(questionsPayload);
        if (qError) console.error("    Question Error:", qError);
    }

    console.log("✅ A1 Upload Complete!");
};

uploadData();
